//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWHSync.RateChangeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Commitments", Namespace="http://schemas.datacontract.org/2004/07/RateChangeOperations.Model")]
    [System.SerializableAttribute()]
    public partial class Commitments : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AccepteRateChangeAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoosterOptInDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChildpreferredNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConstituentRecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HideAcceptRateAndBoosterOptionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsPayerOnDonationBreakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatchTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NeedKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RateChangeActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RateChangeDateFirstInstallmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RateChangeDateFirstInstallment_IncreaseNowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RateChangedAttrExistField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RevenueIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SponsorshipActField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SponsorshipIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupporterBBIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupporterGroupBBIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupporterGroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupporterGroupTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SupporterIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AccepteRateChangeAmount {
            get {
                return this.AccepteRateChangeAmountField;
            }
            set {
                if ((this.AccepteRateChangeAmountField.Equals(value) != true)) {
                    this.AccepteRateChangeAmountField = value;
                    this.RaisePropertyChanged("AccepteRateChangeAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BoosterOptInDate {
            get {
                return this.BoosterOptInDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BoosterOptInDateField, value) != true)) {
                    this.BoosterOptInDateField = value;
                    this.RaisePropertyChanged("BoosterOptInDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChildpreferredName {
            get {
                return this.ChildpreferredNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildpreferredNameField, value) != true)) {
                    this.ChildpreferredNameField = value;
                    this.RaisePropertyChanged("ChildpreferredName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConId {
            get {
                return this.ConIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ConIdField, value) != true)) {
                    this.ConIdField = value;
                    this.RaisePropertyChanged("ConId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConstituentRecordId {
            get {
                return this.ConstituentRecordIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ConstituentRecordIdField, value) != true)) {
                    this.ConstituentRecordIdField = value;
                    this.RaisePropertyChanged("ConstituentRecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((object.ReferenceEquals(this.FrequencyField, value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HideAcceptRateAndBoosterOptions {
            get {
                return this.HideAcceptRateAndBoosterOptionsField;
            }
            set {
                if ((this.HideAcceptRateAndBoosterOptionsField.Equals(value) != true)) {
                    this.HideAcceptRateAndBoosterOptionsField = value;
                    this.RaisePropertyChanged("HideAcceptRateAndBoosterOptions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsPayerOnDonationBreak {
            get {
                return this.IsPayerOnDonationBreakField;
            }
            set {
                if ((object.ReferenceEquals(this.IsPayerOnDonationBreakField, value) != true)) {
                    this.IsPayerOnDonationBreakField = value;
                    this.RaisePropertyChanged("IsPayerOnDonationBreak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatchType {
            get {
                return this.MatchTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MatchTypeField, value) != true)) {
                    this.MatchTypeField = value;
                    this.RaisePropertyChanged("MatchType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NeedKey {
            get {
                return this.NeedKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.NeedKeyField, value) != true)) {
                    this.NeedKeyField = value;
                    this.RaisePropertyChanged("NeedKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethod {
            get {
                return this.PaymentMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentMethodField, value) != true)) {
                    this.PaymentMethodField = value;
                    this.RaisePropertyChanged("PaymentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RateChangeAction {
            get {
                return this.RateChangeActionField;
            }
            set {
                if ((object.ReferenceEquals(this.RateChangeActionField, value) != true)) {
                    this.RateChangeActionField = value;
                    this.RaisePropertyChanged("RateChangeAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RateChangeDateFirstInstallment {
            get {
                return this.RateChangeDateFirstInstallmentField;
            }
            set {
                if ((object.ReferenceEquals(this.RateChangeDateFirstInstallmentField, value) != true)) {
                    this.RateChangeDateFirstInstallmentField = value;
                    this.RaisePropertyChanged("RateChangeDateFirstInstallment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RateChangeDateFirstInstallment_IncreaseNow {
            get {
                return this.RateChangeDateFirstInstallment_IncreaseNowField;
            }
            set {
                if ((object.ReferenceEquals(this.RateChangeDateFirstInstallment_IncreaseNowField, value) != true)) {
                    this.RateChangeDateFirstInstallment_IncreaseNowField = value;
                    this.RaisePropertyChanged("RateChangeDateFirstInstallment_IncreaseNow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RateChangedAttrExist {
            get {
                return this.RateChangedAttrExistField;
            }
            set {
                if ((this.RateChangedAttrExistField.Equals(value) != true)) {
                    this.RateChangedAttrExistField = value;
                    this.RaisePropertyChanged("RateChangedAttrExist");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RevenueId {
            get {
                return this.RevenueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RevenueIdField, value) != true)) {
                    this.RevenueIdField = value;
                    this.RaisePropertyChanged("RevenueId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SponsorshipAct {
            get {
                return this.SponsorshipActField;
            }
            set {
                if ((object.ReferenceEquals(this.SponsorshipActField, value) != true)) {
                    this.SponsorshipActField = value;
                    this.RaisePropertyChanged("SponsorshipAct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SponsorshipId {
            get {
                return this.SponsorshipIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SponsorshipIdField, value) != true)) {
                    this.SponsorshipIdField = value;
                    this.RaisePropertyChanged("SponsorshipId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartDateField, value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupporterBBID {
            get {
                return this.SupporterBBIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SupporterBBIDField, value) != true)) {
                    this.SupporterBBIDField = value;
                    this.RaisePropertyChanged("SupporterBBID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupporterGroupBBID {
            get {
                return this.SupporterGroupBBIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SupporterGroupBBIDField, value) != true)) {
                    this.SupporterGroupBBIDField = value;
                    this.RaisePropertyChanged("SupporterGroupBBID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupporterGroupName {
            get {
                return this.SupporterGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupporterGroupNameField, value) != true)) {
                    this.SupporterGroupNameField = value;
                    this.RaisePropertyChanged("SupporterGroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupporterGroupType {
            get {
                return this.SupporterGroupTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SupporterGroupTypeField, value) != true)) {
                    this.SupporterGroupTypeField = value;
                    this.RaisePropertyChanged("SupporterGroupType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SupporterId {
            get {
                return this.SupporterIdField;
            }
            set {
                if ((this.SupporterIdField.Equals(value) != true)) {
                    this.SupporterIdField = value;
                    this.RaisePropertyChanged("SupporterId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateChange", Namespace="http://schemas.datacontract.org/2004/07/RateChangeOperations.Model")]
    [System.SerializableAttribute()]
    public partial class RateChange : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ExistingRgAmountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] FrequenciesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string assignedAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string constituentRecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int donationAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] increaseByAmountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] needkeysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] nextInstallmentDatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] otherDonationAmountsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] paymentDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string processTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] rateChangeActionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] revenueIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] selectedRateChangeActionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] selectedRateChangeFirstInstallmentDatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] sponsorshipDatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long supporterIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ExistingRgAmounts {
            get {
                return this.ExistingRgAmountsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExistingRgAmountsField, value) != true)) {
                    this.ExistingRgAmountsField = value;
                    this.RaisePropertyChanged("ExistingRgAmounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Frequencies {
            get {
                return this.FrequenciesField;
            }
            set {
                if ((object.ReferenceEquals(this.FrequenciesField, value) != true)) {
                    this.FrequenciesField = value;
                    this.RaisePropertyChanged("Frequencies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string assignedAccount {
            get {
                return this.assignedAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.assignedAccountField, value) != true)) {
                    this.assignedAccountField = value;
                    this.RaisePropertyChanged("assignedAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string constituentRecordId {
            get {
                return this.constituentRecordIdField;
            }
            set {
                if ((object.ReferenceEquals(this.constituentRecordIdField, value) != true)) {
                    this.constituentRecordIdField = value;
                    this.RaisePropertyChanged("constituentRecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int donationAmount {
            get {
                return this.donationAmountField;
            }
            set {
                if ((this.donationAmountField.Equals(value) != true)) {
                    this.donationAmountField = value;
                    this.RaisePropertyChanged("donationAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] increaseByAmounts {
            get {
                return this.increaseByAmountsField;
            }
            set {
                if ((object.ReferenceEquals(this.increaseByAmountsField, value) != true)) {
                    this.increaseByAmountsField = value;
                    this.RaisePropertyChanged("increaseByAmounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] needkeys {
            get {
                return this.needkeysField;
            }
            set {
                if ((object.ReferenceEquals(this.needkeysField, value) != true)) {
                    this.needkeysField = value;
                    this.RaisePropertyChanged("needkeys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] nextInstallmentDates {
            get {
                return this.nextInstallmentDatesField;
            }
            set {
                if ((object.ReferenceEquals(this.nextInstallmentDatesField, value) != true)) {
                    this.nextInstallmentDatesField = value;
                    this.RaisePropertyChanged("nextInstallmentDates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] otherDonationAmounts {
            get {
                return this.otherDonationAmountsField;
            }
            set {
                if ((object.ReferenceEquals(this.otherDonationAmountsField, value) != true)) {
                    this.otherDonationAmountsField = value;
                    this.RaisePropertyChanged("otherDonationAmounts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] paymentDays {
            get {
                return this.paymentDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.paymentDaysField, value) != true)) {
                    this.paymentDaysField = value;
                    this.RaisePropertyChanged("paymentDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string processType {
            get {
                return this.processTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.processTypeField, value) != true)) {
                    this.processTypeField = value;
                    this.RaisePropertyChanged("processType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] rateChangeActions {
            get {
                return this.rateChangeActionsField;
            }
            set {
                if ((object.ReferenceEquals(this.rateChangeActionsField, value) != true)) {
                    this.rateChangeActionsField = value;
                    this.RaisePropertyChanged("rateChangeActions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] revenueIds {
            get {
                return this.revenueIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.revenueIdsField, value) != true)) {
                    this.revenueIdsField = value;
                    this.RaisePropertyChanged("revenueIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] selectedRateChangeActions {
            get {
                return this.selectedRateChangeActionsField;
            }
            set {
                if ((object.ReferenceEquals(this.selectedRateChangeActionsField, value) != true)) {
                    this.selectedRateChangeActionsField = value;
                    this.RaisePropertyChanged("selectedRateChangeActions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] selectedRateChangeFirstInstallmentDates {
            get {
                return this.selectedRateChangeFirstInstallmentDatesField;
            }
            set {
                if ((object.ReferenceEquals(this.selectedRateChangeFirstInstallmentDatesField, value) != true)) {
                    this.selectedRateChangeFirstInstallmentDatesField = value;
                    this.RaisePropertyChanged("selectedRateChangeFirstInstallmentDates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] sponsorshipDates {
            get {
                return this.sponsorshipDatesField;
            }
            set {
                if ((object.ReferenceEquals(this.sponsorshipDatesField, value) != true)) {
                    this.sponsorshipDatesField = value;
                    this.RaisePropertyChanged("sponsorshipDates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long supporterId {
            get {
                return this.supporterIdField;
            }
            set {
                if ((this.supporterIdField.Equals(value) != true)) {
                    this.supporterIdField = value;
                    this.RaisePropertyChanged("supporterId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateChangeResponse", Namespace="http://schemas.datacontract.org/2004/07/RateChangeOperations.Model")]
    [System.SerializableAttribute()]
    public partial class RateChangeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IncidentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NeedKeysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseThreadTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IncidentId {
            get {
                return this.IncidentIdField;
            }
            set {
                if ((this.IncidentIdField.Equals(value) != true)) {
                    this.IncidentIdField = value;
                    this.RaisePropertyChanged("IncidentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NeedKeys {
            get {
                return this.NeedKeysField;
            }
            set {
                if ((object.ReferenceEquals(this.NeedKeysField, value) != true)) {
                    this.NeedKeysField = value;
                    this.RaisePropertyChanged("NeedKeys");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responseThreadText {
            get {
                return this.responseThreadTextField;
            }
            set {
                if ((object.ReferenceEquals(this.responseThreadTextField, value) != true)) {
                    this.responseThreadTextField = value;
                    this.RaisePropertyChanged("responseThreadText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateChangeRequestWebsite", Namespace="http://schemas.datacontract.org/2004/07/RateChangeOperations.Model")]
    [System.SerializableAttribute()]
    public partial class RateChangeRequestWebsite : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBoosterFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SupporterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int donationAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string processTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBoosterFlag {
            get {
                return this.IsBoosterFlagField;
            }
            set {
                if ((this.IsBoosterFlagField.Equals(value) != true)) {
                    this.IsBoosterFlagField = value;
                    this.RaisePropertyChanged("IsBoosterFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SupporterId {
            get {
                return this.SupporterIdField;
            }
            set {
                if ((this.SupporterIdField.Equals(value) != true)) {
                    this.SupporterIdField = value;
                    this.RaisePropertyChanged("SupporterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int donationAmount {
            get {
                return this.donationAmountField;
            }
            set {
                if ((this.donationAmountField.Equals(value) != true)) {
                    this.donationAmountField = value;
                    this.RaisePropertyChanged("donationAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string processType {
            get {
                return this.processTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.processTypeField, value) != true)) {
                    this.processTypeField = value;
                    this.RaisePropertyChanged("processType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RateChangeService.IRateChangeServices")]
    public interface IRateChangeServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/DoWork", ReplyAction="http://tempuri.org/IRateChangeServices/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/DoWork", ReplyAction="http://tempuri.org/IRateChangeServices/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/RateChangeSponsorshipSearch", ReplyAction="http://tempuri.org/IRateChangeServices/RateChangeSponsorshipSearchResponse")]
        DWHSync.RateChangeService.Commitments[] RateChangeSponsorshipSearch(long SupGrpId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/RateChangeSponsorshipSearch", ReplyAction="http://tempuri.org/IRateChangeServices/RateChangeSponsorshipSearchResponse")]
        System.Threading.Tasks.Task<DWHSync.RateChangeService.Commitments[]> RateChangeSponsorshipSearchAsync(long SupGrpId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/RateChange", ReplyAction="http://tempuri.org/IRateChangeServices/RateChangeResponse")]
        DWHSync.RateChangeService.RateChangeResponse[] RateChange(DWHSync.RateChangeService.RateChange arObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/RateChange", ReplyAction="http://tempuri.org/IRateChangeServices/RateChangeResponse")]
        System.Threading.Tasks.Task<DWHSync.RateChangeService.RateChangeResponse[]> RateChangeAsync(DWHSync.RateChangeService.RateChange arObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/NewSponsorshipRateChangeProcess", ReplyAction="http://tempuri.org/IRateChangeServices/NewSponsorshipRateChangeProcessResponse")]
        void NewSponsorshipRateChangeProcess(string LookupId, string SEFGUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/NewSponsorshipRateChangeProcess", ReplyAction="http://tempuri.org/IRateChangeServices/NewSponsorshipRateChangeProcessResponse")]
        System.Threading.Tasks.Task NewSponsorshipRateChangeProcessAsync(string LookupId, string SEFGUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/AddTransferSponsorshipAttribute", ReplyAction="http://tempuri.org/IRateChangeServices/AddTransferSponsorshipAttributeResponse")]
        void AddTransferSponsorshipAttribute(string lookupId, string needKey, string SEFGUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/AddTransferSponsorshipAttribute", ReplyAction="http://tempuri.org/IRateChangeServices/AddTransferSponsorshipAttributeResponse")]
        System.Threading.Tasks.Task AddTransferSponsorshipAttributeAsync(string lookupId, string needKey, string SEFGUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/msExceptionProcess", ReplyAction="http://tempuri.org/IRateChangeServices/msExceptionProcessResponse")]
        DWHSync.RateChangeService.RateChangeResponse[] msExceptionProcess(DWHSync.RateChangeService.RateChange arObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/msExceptionProcess", ReplyAction="http://tempuri.org/IRateChangeServices/msExceptionProcessResponse")]
        System.Threading.Tasks.Task<DWHSync.RateChangeService.RateChangeResponse[]> msExceptionProcessAsync(DWHSync.RateChangeService.RateChange arObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/RateChangeRequestWebsite", ReplyAction="http://tempuri.org/IRateChangeServices/RateChangeRequestWebsiteResponse")]
        void RateChangeRequestWebsite(DWHSync.RateChangeService.RateChangeRequestWebsite rateChangeReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/RateChangeRequestWebsite", ReplyAction="http://tempuri.org/IRateChangeServices/RateChangeRequestWebsiteResponse")]
        System.Threading.Tasks.Task RateChangeRequestWebsiteAsync(DWHSync.RateChangeService.RateChangeRequestWebsite rateChangeReq);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/AddBoosterFlags", ReplyAction="http://tempuri.org/IRateChangeServices/AddBoosterFlagsResponse")]
        DWHSync.RateChangeService.RateChangeResponse[] AddBoosterFlags(DWHSync.RateChangeService.RateChange arObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/AddBoosterFlags", ReplyAction="http://tempuri.org/IRateChangeServices/AddBoosterFlagsResponse")]
        System.Threading.Tasks.Task<DWHSync.RateChangeService.RateChangeResponse[]> AddBoosterFlagsAsync(DWHSync.RateChangeService.RateChange arObj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/UpdateRateChangeManualFlag", ReplyAction="http://tempuri.org/IRateChangeServices/UpdateRateChangeManualFlagResponse")]
        bool UpdateRateChangeManualFlag(long SupporterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/UpdateRateChangeManualFlag", ReplyAction="http://tempuri.org/IRateChangeServices/UpdateRateChangeManualFlagResponse")]
        System.Threading.Tasks.Task<bool> UpdateRateChangeManualFlagAsync(long SupporterId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/addRateChangeAttribute", ReplyAction="http://tempuri.org/IRateChangeServices/addRateChangeAttributeResponse")]
        void addRateChangeAttribute(string attributeName, string revenueId, long RecordId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRateChangeServices/addRateChangeAttribute", ReplyAction="http://tempuri.org/IRateChangeServices/addRateChangeAttributeResponse")]
        System.Threading.Tasks.Task addRateChangeAttributeAsync(string attributeName, string revenueId, long RecordId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRateChangeServicesChannel : DWHSync.RateChangeService.IRateChangeServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RateChangeServicesClient : System.ServiceModel.ClientBase<DWHSync.RateChangeService.IRateChangeServices>, DWHSync.RateChangeService.IRateChangeServices {
        
        public RateChangeServicesClient() {
        }
        
        public RateChangeServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RateChangeServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RateChangeServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RateChangeServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public DWHSync.RateChangeService.Commitments[] RateChangeSponsorshipSearch(long SupGrpId) {
            return base.Channel.RateChangeSponsorshipSearch(SupGrpId);
        }
        
        public System.Threading.Tasks.Task<DWHSync.RateChangeService.Commitments[]> RateChangeSponsorshipSearchAsync(long SupGrpId) {
            return base.Channel.RateChangeSponsorshipSearchAsync(SupGrpId);
        }
        
        public DWHSync.RateChangeService.RateChangeResponse[] RateChange(DWHSync.RateChangeService.RateChange arObj) {
            return base.Channel.RateChange(arObj);
        }
        
        public System.Threading.Tasks.Task<DWHSync.RateChangeService.RateChangeResponse[]> RateChangeAsync(DWHSync.RateChangeService.RateChange arObj) {
            return base.Channel.RateChangeAsync(arObj);
        }
        
        public void NewSponsorshipRateChangeProcess(string LookupId, string SEFGUID) {
            base.Channel.NewSponsorshipRateChangeProcess(LookupId, SEFGUID);
        }
        
        public System.Threading.Tasks.Task NewSponsorshipRateChangeProcessAsync(string LookupId, string SEFGUID) {
            return base.Channel.NewSponsorshipRateChangeProcessAsync(LookupId, SEFGUID);
        }
        
        public void AddTransferSponsorshipAttribute(string lookupId, string needKey, string SEFGUID) {
            base.Channel.AddTransferSponsorshipAttribute(lookupId, needKey, SEFGUID);
        }
        
        public System.Threading.Tasks.Task AddTransferSponsorshipAttributeAsync(string lookupId, string needKey, string SEFGUID) {
            return base.Channel.AddTransferSponsorshipAttributeAsync(lookupId, needKey, SEFGUID);
        }
        
        public DWHSync.RateChangeService.RateChangeResponse[] msExceptionProcess(DWHSync.RateChangeService.RateChange arObj) {
            return base.Channel.msExceptionProcess(arObj);
        }
        
        public System.Threading.Tasks.Task<DWHSync.RateChangeService.RateChangeResponse[]> msExceptionProcessAsync(DWHSync.RateChangeService.RateChange arObj) {
            return base.Channel.msExceptionProcessAsync(arObj);
        }
        
        public void RateChangeRequestWebsite(DWHSync.RateChangeService.RateChangeRequestWebsite rateChangeReq) {
            base.Channel.RateChangeRequestWebsite(rateChangeReq);
        }
        
        public System.Threading.Tasks.Task RateChangeRequestWebsiteAsync(DWHSync.RateChangeService.RateChangeRequestWebsite rateChangeReq) {
            return base.Channel.RateChangeRequestWebsiteAsync(rateChangeReq);
        }
        
        public DWHSync.RateChangeService.RateChangeResponse[] AddBoosterFlags(DWHSync.RateChangeService.RateChange arObj) {
            return base.Channel.AddBoosterFlags(arObj);
        }
        
        public System.Threading.Tasks.Task<DWHSync.RateChangeService.RateChangeResponse[]> AddBoosterFlagsAsync(DWHSync.RateChangeService.RateChange arObj) {
            return base.Channel.AddBoosterFlagsAsync(arObj);
        }
        
        public bool UpdateRateChangeManualFlag(long SupporterId) {
            return base.Channel.UpdateRateChangeManualFlag(SupporterId);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateRateChangeManualFlagAsync(long SupporterId) {
            return base.Channel.UpdateRateChangeManualFlagAsync(SupporterId);
        }
        
        public void addRateChangeAttribute(string attributeName, string revenueId, long RecordId) {
            base.Channel.addRateChangeAttribute(attributeName, revenueId, RecordId);
        }
        
        public System.Threading.Tasks.Task addRateChangeAttributeAsync(string attributeName, string revenueId, long RecordId) {
            return base.Channel.addRateChangeAttributeAsync(attributeName, revenueId, RecordId);
        }
    }
}
